---

- name: Install required packages
  become: true
  yum:
    name: "{{ docker_required_packages | union(docker_required_packages_extra) }}"
    state: present
  tags:
    - install

- name: "Include {{ docker_installation_type }} tasks"
  include: "install_{{ docker_installation_type }}.yml"

- name: Install docker packages
  become: true
  yum:
    name: "{{ docker_packages | union(docker_packages_extra
            + (docker_tarball_bash_completion_enabled | ternary(docker_tarball_bash_completion_packages, []))
            + (vars['docker_%s_packages' | format(docker_installation_type)] | default([]))
          ) }}"
    state: present
