---

- name: Download repo file
  become: true
  get_url:
    url: "{{ docker_package_repo_url }}"
    dest: "/etc/yum.repos.d/{{ docker_package_repo_file }}"
    mode: 0644
    owner: root
    group: root
  tags:
    - install

- name: Enable {{ docker_package_repo_name }} repo
  become: true
  ini_file:
    dest: "/etc/yum.repos.d/{{ docker_package_repo_file }}"
    section: "{{ docker_package_repo_name }}"
    option: enabled
    value: "True"
    no_extra_spaces: true
  tags:
    - install

#
# https://bugzilla.redhat.com/show_bug.cgi?id=1756473
# https://stackoverflow.com/a/60153726
#
- name: Workaround with excluded containerd.io package in RHEL8
  become: true
  ini_file:
    dest: "/etc/yum.repos.d/{{ docker_package_repo_file }}"
    section: "{{ docker_package_repo_name }}"
    option: module_hotfixes
    value: "True"
    no_extra_spaces: true
  tags:
    - install
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"
