---

- name: Include install tasks
  include: install.yml
  tags:
    - install

- name: Ensure directroy /etc/docker is exists
  become: true
  file:
    path: /etc/docker
    state: directory
    mode: 0700
    owner: root
    group: root
  tags:
    - configure

- name: Configure dockerd
  become: true
  copy:
    content: "{{ docker_daemon_json | to_nice_json }}\n"
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root
  notify: systemctl restart-docker
  tags:
    - configure

- name: Detect firewalld is enabled
  systemd:
    name: firewalld
  register: _firewalld

- name: Allow docker0 interface to trusted zone in firewalld
  become: true
  firewalld:
    immediate: true
    interface: docker0
    permanent: true
    state: enabled
    zone: trusted
  when:
    - _firewalld.status.UnitFileState == "enabled"
    - _firewalld.status.SubState == "running"
    - docker_firewalld_trusted | bool

- name: Ensure docker is started and enabled at boot
  become: true
  systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true
