---

- name: Include install tasks
  include: install.yml
  tags:
    - install

- name: Ensure directroy /etc/docker is exists
  become: true
  file:
    path: /etc/docker
    state: directory
    mode: 0700
    owner: root
    group: root
  tags:
    - configure

- name: Configure dockerd
  become: true
  copy:
    content: "{{ docker_daemon_json | to_nice_json }}\n"
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root
  notify: systemctl restart-docker
  tags:
    - configure

- name: Ensure docker is started and enabled at boot
  become: true
  systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true
