---
platforms:
  - &platform-basic
    name: molecule-docker-package-el7-${CI_JOB_ID:-1}
    image: centos:7  # Centos 8 is disabled due systemd bug https://bugzilla.redhat.com/show_bug.cgi?id=1853736
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    stop_signal: SIGRTMIN+3
    privileged: false
    capabilities:
      - SYS_ADMIN  # For systemd
      - NET_ADMIN  # For dockerd
      - SYS_RESOURCE  # For dockerd oom_score_adj
  - <<: *platform-basic
    name: molecule-docker-tarball-fc33-${CI_JOB_ID:-1}
    image: fedora:33
provisioner:
  name: ansible
  inventory:
    host_vars:
      molecule-docker-package-el7-${CI_JOB_ID:-1}:
        ansible_python_interpreter: /usr/bin/python
        docker_installation_type: package
      molecule-docker-tarball-fc33-${CI_JOB_ID:-1}:
        ansible_python_interpreter: /usr/bin/python3
        docker_installation_type: tarball
        docker_compose_required_packages:
          - libxcrypt-compat
  log: true
  config_options:
    defaults:
      stdout_callback: debug
      error_on_undefined_vars: true
      callback_whitelist: profile_tasks
    diff:
      always: true
verifier:
  name: ansible
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --force-color
  flake8
